### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by davidwallis** [genielabs/mig-service-dotnet#12]
Gene,

would you be averse to configuring a build for this with a nuget publish step in to update the existing package on nuget? It would help my interface project builds in that I wouldn't have to specifically reference the local MIG.dll

Again this is easy to do with appveyor, if you want to setup appveyor so that you are the owner, and then configure the team I will happily set it up (its not difficult from what I have played with so for)

David

**Comment by genemars** [comment]
not sure to understand what you're asking :) please explain further

**Comment by genemars** [comment]
Ok I finally did it. =)
